// A photographic interpretation of the scene, not a pixel-registered texture bake.
export const documentaryLook = `Use case: architectural documentary photograph from a spatial layout guide.
Create a completely ordinary, unstaged color photograph of an actual full-size historic mansion interior during an overcast afternoon. A building conservator took this straightforward record photograph on a normal digital camera. The subject is unusual; the photograph itself is utterly matter-of-fact. It must read as a real location with weight, age and construction, not a 3D render or a cinematic image.
Image 1 is a deliberately crude blockout describing the camera, room layout and placement of the main objects. Translate the blockout into real architecture and real manufactured objects. Retain its viewpoint, field of view, architectural boundaries, proportions, tile grid, object locations, broad occlusions and inventory. Do not copy its computer-generated shading, faceting, perfect surfaces or toy-like small shapes. The blockout is not a style reference. Photographic physical plausibility takes priority over matching individual leaf outlines or polygon edges. Keep construction-scale silhouette changes small.
Light: an ordinary overcast afternoon, the same moment in every view. Soft neutral gray daylight enters only through the existing glazed windows and conservatory. Existing windows look out onto a pale clouded sky. Remove the unreal giant moon and replace it with that plain daylight sky. The existing globe lamps and central orrery globe are SWITCHED OFF: unlit, slightly aged opaque white opal glass, no luminous core and no halo. There is no studio lighting, theatrical spotlight, rim light, colored ambient fill or deliberate warm/cool split. Daylight falls off naturally into the rooms. Real corners can be a little dark. Expose for the interior; a window may be slightly overexposed. Do not add windows, doors or lamps to create light.
Shared finishes throughout this single house: matte, muted gray-green painted lime plaster, with only quiet irregularities and occasional hairline settling cracks, not heavy theatrical mottling; warm off-white limestone arches, fluted columns and baseboards with visible fine pores and real joints; dull honey-brown aged brass trim with tarnish in joints and modest handling marks, never glowing gold; alternating ivory limestone and muted green-gray marble floor tiles with fine irregular natural veins, small grout joints, slight unevenness and faint traffic wear. Floors are honed, not mirror-polished. The library remains desaturated slate blue with dark brown walnut shelves, desk and existing red rug. Armchairs have real joined walnut frames, muted dusty-rose woven upholstery, restrained seams, slight cushion compression and normal rounded fabric edges. Keep the same chair design in every angle. Books are ordinary used cloth or leather volumes with varying heights inside the existing shelf divisions, without readable titles. Planters are muted green glazed ceramic with dull brass rims and real dark soil.
Plants are living rubber plants (Ficus elastica), not sculptures or plastic props. Replace the blockout's thick ellipsoid leaves with thin, naturally curved, leathery dark-green leaves attached by petioles to a woody stem; irregular orientation, visible central veins, a few imperfect edges. Preserve the number and location of the potted plants and their approximate overall height and mass. Do not enlarge plants to decorate empty space.
The central brass orrery is a stationary physical museum instrument: its existing large intersecting hoops, central vertical support, exact colored enamel planet inventory and pale limestone pedestal remain in their overall positions. Use plausible thin solid metal profiles, discrete fasteners and joints, slightly uneven patina and real reflected room shapes. Planets are real painted or enamel balls with small surface imperfections. Its central white sphere is unlit opal glass. The low circular plinth and floor compass inlay are aged brass. The orrery is not a light source, floating magic, CGI or a showroom product rendering.
Camera: an unembellished, eye-level wide-angle interior record photo, natural optical perspective, ordinary sensor response, neutral white balance, moderate saturation, realistic tonal range and gentle highlight rolloff. Fine detail is resolved naturally; a little honest sensor noise is acceptable in shade. No film emulation, cinematic grade, HDR processing, bloom, glow, vignette, light shafts, fog, atmospheric drama, bokeh, tilt-shift miniature effect, oversharpening or advertising polish. Do not try to make the room spectacular. Show what is actually there.
Closed inventory: no people, animals, added furniture, artwork, flowers, curtains, rugs, props or decoration. Broad blank walls remain blank. Shallow wall panels are not doorways. Preserve what is visible through each opening; never import another room's objects into this view. Do not copy a reference image's composition. Material reference crops, if supplied, describe only finish and color.
Output one full-bleed 16:9 landscape photograph, with no borders, collage, labels, watermark or readable text. A photograph of a real place is the overriding goal.
`;

export const documentaryDetails = [
  'Front atrium: centered physical brass orrery and limestone pedestal, two fluted stone columns, central arched window with pale overcast sky, library partly visible at far left and conservatory partly visible at far right. Preserve ring layout and all colored planet positions. All white globes are unlit opal glass. Show subtle age without making the mansion derelict.',
  '45-degree view: the orrery is cut off at the LEFT edge; the conservatory arch is right of center. A dusty-rose walnut armchair is near the lower RIGHT; the existing plant appears at the far right. Preserve the room seen through the conservatory arch. Plain overcast sky replaces any moon. Do not add bookshelves to this room.',
  '90-degree side view: conservatory arch at the far LEFT. The large potted rubber plant stays on the RIGHT (roughly x50-79%, y27-94%); the dusty-rose walnut chair is in profile to its LEFT (x30-47%, y58-98%). Keep the right-hand pillar and single unlit wall sconce. Chair must not move to the right of the plant. No extra table or rug.',
  '135-degree rear-wall view: rubber plant occupies the LEFT half; one unlit sconce near center, limestone pier at center, broad shallow wall panel on the RIGHT. A small brass ceiling-ring arc is cut by the top edge. NO doorway, arch opening, window or chair is visible. Maintain the sparse wall composition.',
  '180-degree view: a close view of the rear atrium wall, intentionally sparse. A large shallow gray-green inset wall panel is centered (x24-76%). Its darker same-family paint remains green-gray, not a blue door. The cropped lower arc of an overhead brass ring runs across the top. No furniture, plants, sconces, doorways or windows are visible. Do not invent floor where the source is cropped.',
  '225-degree rear-wall view: broad shallow wall panel on the LEFT, limestone pier near center, one unlit sconce just to its right, large potted rubber plant on the RIGHT. No opening, window or chair is visible. Panel is a subtly darker gray-green paint, not a door.',
  '270-degree side view: large rubber plant on the LEFT (x25-50%), profile dusty-rose walnut chair center-RIGHT (x53-71%), library arch at far RIGHT (x70-99%). Through that arch are walnut bookshelves, a small unlit wall lamp, desk and part of the existing red rug against slate-blue library walls. NO rectangular window is visible within this library opening. Preserve the chair and plant ordering.',
  '315-degree view: near dusty-rose walnut armchair cut off at lower LEFT, library arch left of center with walnut shelves and slate-blue walls, fluted stone column right of center, partial brass orrery cut off on the RIGHT. Its tall pedestal is limestone and its low circular plinth is brass. Match the first atrium photograph, including all unlit white globes and neutral overcast daylight.',
];
